services:

  frontend:
    build:
      context: ./react_query_frontend
    container_name: react-frontend

  json-server:
    build:
      context: ./json-server
    container_name: react-json-server
    ports:
      - "3001:3001"

  nginx:
    build:
      context: ./nginx
    container_name: react-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - json-server