version: '3.9'

services:

  frontend:
    build:
      context: ./react_query_frontend
    container_name: react-frontend

  json-server:
    build:
      context: ./react_query_frontend/server
    container_name: react-json-server

  nginx:
    build:
      context: ./nginx
    container_name: react-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - json-server

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home: